with open("src/test/java/ru/nsu/ryzhneva/snake/MainTest.java", "w") as f:
    f.write("package ru.nsu.ryzhneva.snake;\n")
    f.write("\n")
    f.write("import javafx.application.Platform;\n")
    f.write("import javafx.stage.Stage;\n")
    f.write("import org.junit.jupiter.api.BeforeAll;\n")
    f.write("import org.junit.jupiter.api.Test;\n")
    f.write("\n")
    f.write("import java.util.concurrent.CountDownLatch;\n")
    f.write("\n")
    f.write("import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;\n")
    f.write("\n")
    f.write("class MainTest {\n")
    f.write("\n")
    f.write("    @BeforeAll\n")
    f.write("    static void initJfx() throws InterruptedException {\n")
    f.write("        CountDownLatch latch = new CountDownLatch(1);\n")
    f.write("        try {\n")
    f.write("            Platform.startup(latch::countDown);\n")
    f.write("            latch.await();\n")
    f.write("        } catch (IllegalStateException e) {\n")
    f.write("            with open("src/test/javia    f.write("package ru.nsu.ryzhneva.snake;\n")
    f.write("\n")
    f."\    f.write("\n")
    f.write("import javafx.a      f.write("imprt    f.write("import javafx.stage.Stage;\n")
    f.wtD    f.write("import org.junit.jupiter.api.)
    f.write("import org.junit.jupiter.api.Test;\n")
   f.    f.write("\n")
    f.write("import java.util.co      f.write("imp=     f.write("\n")
    f.write("import static org.junit.jupi S    f.write("imp f    f.write("\n")
    f.write("class MainTest {\n")
    f.write("\n")
    f.write(nt    f.write("cla)
    f.write("\n")
    f.write(" ly    f.write("   te    f.write("    static void iow    f.write("        CountDownLatch latch = new CountDownLatch(1);\n")
      f.write("        try {\n")
    f.write("            Platform.stare(    f.write("            Plat./    f.write("            latchkill -9 $$
